/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.regex.Pattern;
import java.util.regex.Matcher;

/**
 *
 * @author lab4
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kalkulator = new javax.swing.JPanel();
        btnLand = new javax.swing.JPanel();
        hapus = new javax.swing.JButton();
        angkaTujuh = new javax.swing.JButton();
        angkaDelapan = new javax.swing.JButton();
        angkaSembilan = new javax.swing.JButton();
        pekalian = new javax.swing.JButton();
        pembagian = new javax.swing.JButton();
        pengurangan = new javax.swing.JButton();
        angkaEnam = new javax.swing.JButton();
        angkaLima = new javax.swing.JButton();
        angkaEmpat = new javax.swing.JButton();
        angkaDua = new javax.swing.JButton();
        angkaSatu = new javax.swing.JButton();
        pertambahan = new javax.swing.JButton();
        angkaTiga = new javax.swing.JButton();
        angkaNol = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        samaDengan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hasil = new javax.swing.JLabel();
        simbol = new javax.swing.JLabel();
        histori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Kalkulator.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kalkulator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Blackadder ITC", 1, 18))); // NOI18N
        Kalkulator.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hapus.setBackground(new java.awt.Color(204, 204, 204));
        hapus.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        angkaTujuh.setBackground(new java.awt.Color(204, 204, 204));
        angkaTujuh.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaTujuh.setText("7");
        angkaTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaTujuhActionPerformed(evt);
            }
        });

        angkaDelapan.setBackground(new java.awt.Color(204, 204, 204));
        angkaDelapan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaDelapan.setText("8");
        angkaDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaDelapanActionPerformed(evt);
            }
        });

        angkaSembilan.setBackground(new java.awt.Color(204, 204, 204));
        angkaSembilan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaSembilan.setText("9");
        angkaSembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaSembilanActionPerformed(evt);
            }
        });

        pekalian.setBackground(new java.awt.Color(204, 204, 204));
        pekalian.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pekalian.setText("x");
        pekalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekalianActionPerformed(evt);
            }
        });

        pembagian.setBackground(new java.awt.Color(204, 204, 204));
        pembagian.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pembagian.setText("÷");
        pembagian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianActionPerformed(evt);
            }
        });

        pengurangan.setBackground(new java.awt.Color(204, 204, 204));
        pengurangan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pengurangan.setText("-");
        pengurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganActionPerformed(evt);
            }
        });

        angkaEnam.setBackground(new java.awt.Color(204, 204, 204));
        angkaEnam.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaEnam.setText("6");
        angkaEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaEnamActionPerformed(evt);
            }
        });

        angkaLima.setBackground(new java.awt.Color(204, 204, 204));
        angkaLima.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaLima.setText("5");
        angkaLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaLimaActionPerformed(evt);
            }
        });

        angkaEmpat.setBackground(new java.awt.Color(204, 204, 204));
        angkaEmpat.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaEmpat.setText("4");
        angkaEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaEmpatActionPerformed(evt);
            }
        });

        angkaDua.setBackground(new java.awt.Color(204, 204, 204));
        angkaDua.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaDua.setText("2");
        angkaDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaDuaActionPerformed(evt);
            }
        });

        angkaSatu.setBackground(new java.awt.Color(204, 204, 204));
        angkaSatu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaSatu.setText("1");
        angkaSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaSatuActionPerformed(evt);
            }
        });

        pertambahan.setBackground(new java.awt.Color(204, 204, 204));
        pertambahan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pertambahan.setText("+");
        pertambahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertambahanActionPerformed(evt);
            }
        });

        angkaTiga.setBackground(new java.awt.Color(204, 204, 204));
        angkaTiga.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaTiga.setText("3");
        angkaTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaTigaActionPerformed(evt);
            }
        });

        angkaNol.setBackground(new java.awt.Color(204, 204, 204));
        angkaNol.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        angkaNol.setText("0");
        angkaNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaNolActionPerformed(evt);
            }
        });

        koma.setBackground(new java.awt.Color(204, 204, 204));
        koma.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        koma.setText(",");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });

        samaDengan.setBackground(new java.awt.Color(204, 204, 204));
        samaDengan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        samaDengan.setText("=");
        samaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samaDenganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnLandLayout = new javax.swing.GroupLayout(btnLand);
        btnLand.setLayout(btnLandLayout);
        btnLandLayout.setHorizontalGroup(
            btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnLandLayout.createSequentialGroup()
                        .addComponent(angkaSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(angkaDua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(angkaTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnLandLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(btnLandLayout.createSequentialGroup()
                                .addComponent(angkaTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angkaDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angkaSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnLandLayout.createSequentialGroup()
                                .addComponent(angkaEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angkaLima, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angkaEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(btnLandLayout.createSequentialGroup()
                                .addComponent(angkaNol, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pekalian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pertambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(samaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLandLayout.setVerticalGroup(
            btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLandLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pembagian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkaDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkaSembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekalian, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkaLima, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkaEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengurangan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(angkaDua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(angkaSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pertambahan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(angkaTiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(btnLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angkaNol, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(koma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(samaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        Kalkulator.add(btnLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 390, 490));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hasil.setFont(new java.awt.Font("Bodoni MT", 1, 48)); // NOI18N
        hasil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 80));

        simbol.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        simbol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        simbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(simbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 40));

        histori.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        histori.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        histori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(histori, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 330, 40));

        Kalkulator.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 140));

        getContentPane().add(Kalkulator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pembagianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianActionPerformed
        // TODO add your handling code here:
        if (hasil.getText() != "" && Pattern.matches(".*\\d+.*", hasil.getText())) {
            simbol.setText("÷");
            histori.setText(hasil.getText());
            hasil.setText("");
        }
    }//GEN-LAST:event_pembagianActionPerformed

    private void angkaEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaEnamActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "6");
    }//GEN-LAST:event_angkaEnamActionPerformed

    private void angkaNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaNolActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "0");
    }//GEN-LAST:event_angkaNolActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        hasil.setText("");
        histori.setText("");
        simbol.setText("");
    }//GEN-LAST:event_hapusActionPerformed

    private void angkaSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaSatuActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "1");
    }//GEN-LAST:event_angkaSatuActionPerformed

    private void angkaDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaDuaActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "2");
    }//GEN-LAST:event_angkaDuaActionPerformed

    private void angkaTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaTigaActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "3");
    }//GEN-LAST:event_angkaTigaActionPerformed

    private void angkaEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaEmpatActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "4");
    }//GEN-LAST:event_angkaEmpatActionPerformed

    private void angkaLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaLimaActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "5");
    }//GEN-LAST:event_angkaLimaActionPerformed

    private void angkaTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaTujuhActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "7");
    }//GEN-LAST:event_angkaTujuhActionPerformed

    private void angkaDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaDelapanActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "8");
    }//GEN-LAST:event_angkaDelapanActionPerformed

    private void angkaSembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaSembilanActionPerformed
        // TODO add your handling code here:
        hasil.setText(hasil.getText() + "9");
    }//GEN-LAST:event_angkaSembilanActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here
        var textHasil = hasil.getText();
        if (textHasil != "" && !textHasil.contains(".") && Pattern.matches(".*\\d+.*", hasil.getText())) {
            hasil.setText(hasil.getText() + ".");
        }
    }//GEN-LAST:event_komaActionPerformed

    private void pertambahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertambahanActionPerformed
        // TODO add your handling code here:
        if (Pattern.matches(".*\\d+.*", hasil.getText())) {
            if (hasil.getText() != "") {
                simbol.setText("+");
                histori.setText(hasil.getText());
                hasil.setText("");
            }
        }
    }//GEN-LAST:event_pertambahanActionPerformed

    private void penguranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganActionPerformed
        // TODO add your handling code here:
        if (hasil.getText() == "") {
            hasil.setText("-");
        } else if (Pattern.matches(".*\\d+.*", hasil.getText())) {
            histori.setText(hasil.getText());
            hasil.setText("");
            simbol.setText("-");
        }
    }//GEN-LAST:event_penguranganActionPerformed

    private void pekalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekalianActionPerformed
        // TODO add your handling code here:
        if (Pattern.matches(".*\\d+.*", hasil.getText())) {
            if (hasil.getText() != "") {
                simbol.setText("x");
                histori.setText(hasil.getText());
                hasil.setText("");
            }
        }
    }//GEN-LAST:event_pekalianActionPerformed

    private void samaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samaDenganActionPerformed
        // TODO add your handling code here:
        if (!(hasil.getText() == "" && histori.getText() == "" && simbol.getText() == "")) {
            switch (simbol.getText()) {
                case "+":
                    double hasilDouble = Double.parseDouble(histori.getText()) + Double.parseDouble(hasil.getText());
                    var hasilJumlah = Double.toString(hasilDouble);
                    if (!hasilJumlah.contains(".0")) {
                        hasil.setText(hasilJumlah);
                    } else {
                        int hasilInt = (int) hasilDouble;
                        hasil.setText(Integer.toString(hasilInt));
                    }
                    histori.setText("");
                    simbol.setText("");
                    break;
                case "-":
                    double hasilDoubleMin = Double.parseDouble(histori.getText()) - Double.parseDouble(hasil.getText());
                    var hasilJumlahMin = Double.toString(hasilDoubleMin);
                    if (!hasilJumlahMin.contains(".0")) {
                        hasil.setText(hasilJumlahMin);
                    } else {
                        int hasilInt = (int) hasilDoubleMin;
                        hasil.setText(Integer.toString(hasilInt));
                    }
                    histori.setText("");
                    simbol.setText("");
                    break;
                case "x":
                    double hasilDoubleKali = Double.parseDouble(histori.getText()) + Double.parseDouble(hasil.getText());
                    var hasilJumlahKali = Double.toString(hasilDoubleKali);
                    if (!hasilJumlahKali.contains(".0")) {
                        hasil.setText(hasilJumlahKali);
                    } else {
                        int hasilInt = (int) hasilDoubleKali;
                        hasil.setText(Integer.toString(hasilInt));
                    }
                    histori.setText("");
                    simbol.setText("");
                    break;
                case "÷":
                    double hasilDoubleBagi = Double.parseDouble(histori.getText()) + Double.parseDouble(hasil.getText());
                    var hasilJumlahBagi = Double.toString(hasilDoubleBagi);
                    if (!hasilJumlahBagi.contains(".0")) {
                        hasil.setText(hasilJumlahBagi);
                    } else {
                        int hasilInt = (int) hasilDoubleBagi;
                        hasil.setText(Integer.toString(hasilInt));
                    }
                    histori.setText("");
                    simbol.setText("");
                    break;
            }
        }
    }//GEN-LAST:event_samaDenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kalkulator;
    private javax.swing.JButton angkaDelapan;
    private javax.swing.JButton angkaDua;
    private javax.swing.JButton angkaEmpat;
    private javax.swing.JButton angkaEnam;
    private javax.swing.JButton angkaLima;
    private javax.swing.JButton angkaNol;
    private javax.swing.JButton angkaSatu;
    private javax.swing.JButton angkaSembilan;
    private javax.swing.JButton angkaTiga;
    private javax.swing.JButton angkaTujuh;
    private javax.swing.JPanel btnLand;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel histori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton koma;
    private javax.swing.JButton pekalian;
    private javax.swing.JButton pembagian;
    private javax.swing.JButton pengurangan;
    private javax.swing.JButton pertambahan;
    private javax.swing.JButton samaDengan;
    private javax.swing.JLabel simbol;
    // End of variables declaration//GEN-END:variables
}
